/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as TestErrorRouteImport } from './routes/test-error'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as AuthCheckEmailRouteImport } from './routes/auth/check-email'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as DeviceApproveRouteImport } from './routes/device/approve'
import { Route as InvoiceInvoiceIdRouteImport } from './routes/invoice.$invoiceId'
import { Route as McpAuthorizeRouteImport } from './routes/mcp.authorize'
import { Route as PostTokenRouteImport } from './routes/post.$token'
import { Route as LayoutAuthenticatedActivityRouteImport } from './routes/_layout/_authenticated/activity'
import { Route as LayoutAuthenticatedAdministrationRouteImport } from './routes/_layout/_authenticated/administration'
import { Route as LayoutAuthenticatedBoardRouteImport } from './routes/_layout/_authenticated/board'
import { Route as LayoutAuthenticatedCommunicationsRouteImport } from './routes/_layout/_authenticated/communications'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/dashboard'
import { Route as LayoutAuthenticatedDialerRouteImport } from './routes/_layout/_authenticated/dialer'
import { Route as LayoutAuthenticatedEmailsRouteImport } from './routes/_layout/_authenticated/emails'
import { Route as LayoutAuthenticatedEmployeesRouteImport } from './routes/_layout/_authenticated/employees'
import { Route as LayoutAuthenticatedFinderRouteImport } from './routes/_layout/_authenticated/finder'
import { Route as LayoutAuthenticatedHomeRouteImport } from './routes/_layout/_authenticated/home'
import { Route as LayoutAuthenticatedInboundRouteImport } from './routes/_layout/_authenticated/inbound'
import { Route as LayoutAuthenticatedInboxesRouteImport } from './routes/_layout/_authenticated/inboxes'
import { Route as LayoutAuthenticatedInvitationsRouteImport } from './routes/_layout/_authenticated/invitations'
import { Route as LayoutAuthenticatedInvoicesRouteImport } from './routes/_layout/_authenticated/invoices'
import { Route as LayoutAuthenticatedLeadsRouteImport } from './routes/_layout/_authenticated/leads'
import { Route as LayoutAuthenticatedMarketingRouteImport } from './routes/_layout/_authenticated/marketing'
import { Route as LayoutAuthenticatedOnboardingRouteImport } from './routes/_layout/_authenticated/onboarding'
import { Route as LayoutAuthenticatedOrdersRouteImport } from './routes/_layout/_authenticated/orders'
import { Route as LayoutAuthenticatedPipelineRouteImport } from './routes/_layout/_authenticated/pipeline'
import { Route as LayoutAuthenticatedPipelineSettingsRouteImport } from './routes/_layout/_authenticated/pipeline-settings'
import { Route as LayoutAuthenticatedProfileSetupRouteImport } from './routes/_layout/_authenticated/profile-setup'
import { Route as LayoutAuthenticatedProposalsRouteImport } from './routes/_layout/_authenticated/proposals'
import { Route as LayoutAuthenticatedSchedulerRouteImport } from './routes/_layout/_authenticated/scheduler'
import { Route as InvitationAcceptInviteIdRouteImport } from './routes/invitation/accept.$inviteId'
import { Route as PortalClaimTokenRouteImport } from './routes/portal.claim.$token'
import { Route as ProposalNumberSlugRouteImport } from './routes/proposal.$number.$slug'
import { Route as STTaskIdRouteImport } from './routes/s.t.$taskId'
import { Route as LayoutAuthenticatedDashboardIndexRouteImport } from './routes/_layout/_authenticated/dashboard/index'
import { Route as LayoutAuthenticatedDashboardInvitationsRouteImport } from './routes/_layout/_authenticated/dashboard/invitations'
import { Route as LayoutAuthenticatedDashboardSettingsRouteImport } from './routes/_layout/_authenticated/dashboard/settings'
import { Route as LayoutAuthenticatedLeadsKanbanRouteImport } from './routes/_layout/_authenticated/leads_.kanban'
import { Route as LayoutAuthenticatedMarketingComposeRouteImport } from './routes/_layout/_authenticated/marketing_.compose'
import { Route as LayoutAuthenticatedPipelineAccountIdRouteImport } from './routes/_layout/_authenticated/pipeline_.$accountId'
import { Route as LayoutAuthenticatedProposalsProposalIdRouteImport } from './routes/_layout/_authenticated/proposals_.$proposalId'
import { Route as LayoutAuthenticatedDashboardSettingsAccountRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId'
import { Route as LayoutAuthenticatedDashboardWorkspaceCreateRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/create'
import { Route as LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/developer'
import { Route as LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/information'
import { Route as LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/notifications'
import { Route as LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/preferences'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace/general'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceLabelsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace/labels'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceRolesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace/roles'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdAccessRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/access'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/general'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/gantt'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeviceRoute,
} as any)
const DeviceApproveRoute = DeviceApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => DeviceRoute,
} as any)
const InvoiceInvoiceIdRoute = InvoiceInvoiceIdRouteImport.update({
  id: '/invoice/$invoiceId',
  path: '/invoice/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const McpAuthorizeRoute = McpAuthorizeRouteImport.update({
  id: '/mcp/authorize',
  path: '/mcp/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const PostTokenRoute = PostTokenRouteImport.update({
  id: '/post/$token',
  path: '/post/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthenticatedActivityRoute =
  LayoutAuthenticatedActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAdministrationRoute =
  LayoutAuthenticatedAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedBoardRoute =
  LayoutAuthenticatedBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedCommunicationsRoute =
  LayoutAuthenticatedCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDialerRoute =
  LayoutAuthenticatedDialerRouteImport.update({
    id: '/dialer',
    path: '/dialer',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedEmailsRoute =
  LayoutAuthenticatedEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedEmployeesRoute =
  LayoutAuthenticatedEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedFinderRoute =
  LayoutAuthenticatedFinderRouteImport.update({
    id: '/finder',
    path: '/finder',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedHomeRoute = LayoutAuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutAuthenticatedRoute,
} as any)
const LayoutAuthenticatedInboundRoute =
  LayoutAuthenticatedInboundRouteImport.update({
    id: '/inbound',
    path: '/inbound',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedInboxesRoute =
  LayoutAuthenticatedInboxesRouteImport.update({
    id: '/inboxes',
    path: '/inboxes',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedInvitationsRoute =
  LayoutAuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedInvoicesRoute =
  LayoutAuthenticatedInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedLeadsRoute =
  LayoutAuthenticatedLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedMarketingRoute =
  LayoutAuthenticatedMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOnboardingRoute =
  LayoutAuthenticatedOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOrdersRoute =
  LayoutAuthenticatedOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedPipelineRoute =
  LayoutAuthenticatedPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedPipelineSettingsRoute =
  LayoutAuthenticatedPipelineSettingsRouteImport.update({
    id: '/pipeline-settings',
    path: '/pipeline-settings',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedProfileSetupRoute =
  LayoutAuthenticatedProfileSetupRouteImport.update({
    id: '/profile-setup',
    path: '/profile-setup',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedProposalsRoute =
  LayoutAuthenticatedProposalsRouteImport.update({
    id: '/proposals',
    path: '/proposals',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedSchedulerRoute =
  LayoutAuthenticatedSchedulerRouteImport.update({
    id: '/scheduler',
    path: '/scheduler',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const InvitationAcceptInviteIdRoute =
  InvitationAcceptInviteIdRouteImport.update({
    id: '/invitation/accept/$inviteId',
    path: '/invitation/accept/$inviteId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalClaimTokenRoute = PortalClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => PortalRoute,
} as any)
const ProposalNumberSlugRoute = ProposalNumberSlugRouteImport.update({
  id: '/proposal/$number/$slug',
  path: '/proposal/$number/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const STTaskIdRoute = STTaskIdRouteImport.update({
  id: '/s/t/$taskId',
  path: '/s/t/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthenticatedDashboardIndexRoute =
  LayoutAuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardInvitationsRoute =
  LayoutAuthenticatedDashboardInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsRoute =
  LayoutAuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedLeadsKanbanRoute =
  LayoutAuthenticatedLeadsKanbanRouteImport.update({
    id: '/leads_/kanban',
    path: '/leads/kanban',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedMarketingComposeRoute =
  LayoutAuthenticatedMarketingComposeRouteImport.update({
    id: '/marketing_/compose',
    path: '/marketing/compose',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedPipelineAccountIdRoute =
  LayoutAuthenticatedPipelineAccountIdRouteImport.update({
    id: '/pipeline_/$accountId',
    path: '/pipeline/$accountId',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedProposalsProposalIdRoute =
  LayoutAuthenticatedProposalsProposalIdRouteImport.update({
    id: '/proposals_/$proposalId',
    path: '/proposals/$proposalId',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountRoute =
  LayoutAuthenticatedDashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsProjectsRoute =
  LayoutAuthenticatedDashboardSettingsProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsWorkspaceRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceCreateRoute =
  LayoutAuthenticatedDashboardWorkspaceCreateRouteImport.update({
    id: '/workspace/create',
    path: '/workspace/create',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute =
  LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountInformationRoute =
  LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport.update({
    id: '/information',
    path: '/information',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute =
  LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute =
  LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsWorkspaceRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsWorkspaceLabelsRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceLabelsRouteImport.update({
    id: '/labels',
    path: '/labels',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsWorkspaceRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsWorkspaceRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdAccessRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdAccessRouteImport.update(
    {
      id: '/$projectId/access',
      path: '/$projectId/access',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRouteImport.update(
    {
      id: '/$projectId/general',
      path: '/$projectId/general',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRouteImport.update(
    {
      id: '/$projectId/integrations',
      path: '/$projectId/integrations',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRouteImport.update(
    {
      id: '/$projectId/workflow',
      path: '/$projectId/workflow',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRouteImport.update(
    {
      id: '/project/$projectId/',
      path: '/project/$projectId/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRouteImport.update(
    {
      id: '/project/$projectId/backlog',
      path: '/project/$projectId/backlog',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRouteImport.update(
    {
      id: '/project/$projectId/board',
      path: '/project/$projectId/board',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRouteImport.update(
    {
      id: '/project/$projectId/gantt',
      path: '/project/$projectId/gantt',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRouteImport.update(
    {
      id: '/project/$projectId/task/$taskId_',
      path: '/project/$projectId/task/$taskId',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/device': typeof DeviceRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/invoice/$invoiceId': typeof InvoiceInvoiceIdRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/post/$token': typeof PostTokenRoute
  '/device/': typeof DeviceIndexRoute
  '/activity': typeof LayoutAuthenticatedActivityRoute
  '/administration': typeof LayoutAuthenticatedAdministrationRoute
  '/board': typeof LayoutAuthenticatedBoardRoute
  '/communications': typeof LayoutAuthenticatedCommunicationsRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/dialer': typeof LayoutAuthenticatedDialerRoute
  '/emails': typeof LayoutAuthenticatedEmailsRoute
  '/employees': typeof LayoutAuthenticatedEmployeesRoute
  '/finder': typeof LayoutAuthenticatedFinderRoute
  '/home': typeof LayoutAuthenticatedHomeRoute
  '/inbound': typeof LayoutAuthenticatedInboundRoute
  '/inboxes': typeof LayoutAuthenticatedInboxesRoute
  '/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/invoices': typeof LayoutAuthenticatedInvoicesRoute
  '/leads': typeof LayoutAuthenticatedLeadsRoute
  '/marketing': typeof LayoutAuthenticatedMarketingRoute
  '/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/orders': typeof LayoutAuthenticatedOrdersRoute
  '/pipeline': typeof LayoutAuthenticatedPipelineRoute
  '/pipeline-settings': typeof LayoutAuthenticatedPipelineSettingsRoute
  '/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/proposals': typeof LayoutAuthenticatedProposalsRoute
  '/scheduler': typeof LayoutAuthenticatedSchedulerRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/portal/claim/$token': typeof PortalClaimTokenRoute
  '/proposal/$number/$slug': typeof ProposalNumberSlugRoute
  '/s/t/$taskId': typeof STTaskIdRoute
  '/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/leads/kanban': typeof LayoutAuthenticatedLeadsKanbanRoute
  '/marketing/compose': typeof LayoutAuthenticatedMarketingComposeRoute
  '/pipeline/$accountId': typeof LayoutAuthenticatedPipelineAccountIdRoute
  '/proposals/$proposalId': typeof LayoutAuthenticatedProposalsProposalIdRoute
  '/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/dashboard/settings/projects': typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  '/dashboard/settings/workspace': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
  '/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  '/dashboard/workspace/create': typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
  '/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/dashboard/settings/workspace/general': typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  '/dashboard/settings/workspace/labels': typeof LayoutAuthenticatedDashboardSettingsWorkspaceLabelsRoute
  '/dashboard/settings/workspace/roles': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute
  '/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/dashboard/workspace/$workspaceId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/dashboard/settings/projects/$projectId/access': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdAccessRoute
  '/dashboard/settings/projects/$projectId/general': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  '/dashboard/settings/projects/$projectId/integrations': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  '/dashboard/settings/projects/$projectId/workflow': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/gantt': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/invoice/$invoiceId': typeof InvoiceInvoiceIdRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/post/$token': typeof PostTokenRoute
  '/device': typeof DeviceIndexRoute
  '/activity': typeof LayoutAuthenticatedActivityRoute
  '/administration': typeof LayoutAuthenticatedAdministrationRoute
  '/board': typeof LayoutAuthenticatedBoardRoute
  '/communications': typeof LayoutAuthenticatedCommunicationsRoute
  '/dialer': typeof LayoutAuthenticatedDialerRoute
  '/emails': typeof LayoutAuthenticatedEmailsRoute
  '/employees': typeof LayoutAuthenticatedEmployeesRoute
  '/finder': typeof LayoutAuthenticatedFinderRoute
  '/home': typeof LayoutAuthenticatedHomeRoute
  '/inbound': typeof LayoutAuthenticatedInboundRoute
  '/inboxes': typeof LayoutAuthenticatedInboxesRoute
  '/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/invoices': typeof LayoutAuthenticatedInvoicesRoute
  '/leads': typeof LayoutAuthenticatedLeadsRoute
  '/marketing': typeof LayoutAuthenticatedMarketingRoute
  '/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/orders': typeof LayoutAuthenticatedOrdersRoute
  '/pipeline': typeof LayoutAuthenticatedPipelineRoute
  '/pipeline-settings': typeof LayoutAuthenticatedPipelineSettingsRoute
  '/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/proposals': typeof LayoutAuthenticatedProposalsRoute
  '/scheduler': typeof LayoutAuthenticatedSchedulerRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/portal/claim/$token': typeof PortalClaimTokenRoute
  '/proposal/$number/$slug': typeof ProposalNumberSlugRoute
  '/s/t/$taskId': typeof STTaskIdRoute
  '/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/leads/kanban': typeof LayoutAuthenticatedLeadsKanbanRoute
  '/marketing/compose': typeof LayoutAuthenticatedMarketingComposeRoute
  '/pipeline/$accountId': typeof LayoutAuthenticatedPipelineAccountIdRoute
  '/proposals/$proposalId': typeof LayoutAuthenticatedProposalsProposalIdRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/dashboard/settings/projects': typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  '/dashboard/settings/workspace': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
  '/dashboard/workspace/create': typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
  '/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/dashboard/settings/workspace/general': typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  '/dashboard/settings/workspace/labels': typeof LayoutAuthenticatedDashboardSettingsWorkspaceLabelsRoute
  '/dashboard/settings/workspace/roles': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute
  '/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/dashboard/settings/projects/$projectId/access': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdAccessRoute
  '/dashboard/settings/projects/$projectId/general': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  '/dashboard/settings/projects/$projectId/integrations': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  '/dashboard/settings/projects/$projectId/workflow': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/gantt': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute
  '/dashboard/workspace/$workspaceId/project/$projectId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/device': typeof DeviceRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/invoice/$invoiceId': typeof InvoiceInvoiceIdRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/post/$token': typeof PostTokenRoute
  '/device/': typeof DeviceIndexRoute
  '/_layout/_authenticated/activity': typeof LayoutAuthenticatedActivityRoute
  '/_layout/_authenticated/administration': typeof LayoutAuthenticatedAdministrationRoute
  '/_layout/_authenticated/board': typeof LayoutAuthenticatedBoardRoute
  '/_layout/_authenticated/communications': typeof LayoutAuthenticatedCommunicationsRoute
  '/_layout/_authenticated/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/_layout/_authenticated/dialer': typeof LayoutAuthenticatedDialerRoute
  '/_layout/_authenticated/emails': typeof LayoutAuthenticatedEmailsRoute
  '/_layout/_authenticated/employees': typeof LayoutAuthenticatedEmployeesRoute
  '/_layout/_authenticated/finder': typeof LayoutAuthenticatedFinderRoute
  '/_layout/_authenticated/home': typeof LayoutAuthenticatedHomeRoute
  '/_layout/_authenticated/inbound': typeof LayoutAuthenticatedInboundRoute
  '/_layout/_authenticated/inboxes': typeof LayoutAuthenticatedInboxesRoute
  '/_layout/_authenticated/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/_layout/_authenticated/invoices': typeof LayoutAuthenticatedInvoicesRoute
  '/_layout/_authenticated/leads': typeof LayoutAuthenticatedLeadsRoute
  '/_layout/_authenticated/marketing': typeof LayoutAuthenticatedMarketingRoute
  '/_layout/_authenticated/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/_layout/_authenticated/orders': typeof LayoutAuthenticatedOrdersRoute
  '/_layout/_authenticated/pipeline': typeof LayoutAuthenticatedPipelineRoute
  '/_layout/_authenticated/pipeline-settings': typeof LayoutAuthenticatedPipelineSettingsRoute
  '/_layout/_authenticated/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/_layout/_authenticated/proposals': typeof LayoutAuthenticatedProposalsRoute
  '/_layout/_authenticated/scheduler': typeof LayoutAuthenticatedSchedulerRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/portal/claim/$token': typeof PortalClaimTokenRoute
  '/proposal/$number/$slug': typeof ProposalNumberSlugRoute
  '/s/t/$taskId': typeof STTaskIdRoute
  '/_layout/_authenticated/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/_layout/_authenticated/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/_layout/_authenticated/leads_/kanban': typeof LayoutAuthenticatedLeadsKanbanRoute
  '/_layout/_authenticated/marketing_/compose': typeof LayoutAuthenticatedMarketingComposeRoute
  '/_layout/_authenticated/pipeline_/$accountId': typeof LayoutAuthenticatedPipelineAccountIdRoute
  '/_layout/_authenticated/proposals_/$proposalId': typeof LayoutAuthenticatedProposalsProposalIdRoute
  '/_layout/_authenticated/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/_layout/_authenticated/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/_layout/_authenticated/dashboard/settings/projects': typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  '/_layout/_authenticated/dashboard/settings/workspace': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
  '/_layout/_authenticated/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  '/_layout/_authenticated/dashboard/workspace/create': typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
  '/_layout/_authenticated/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/_layout/_authenticated/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/_layout/_authenticated/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/_layout/_authenticated/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/_layout/_authenticated/dashboard/settings/workspace/general': typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  '/_layout/_authenticated/dashboard/settings/workspace/labels': typeof LayoutAuthenticatedDashboardSettingsWorkspaceLabelsRoute
  '/_layout/_authenticated/dashboard/settings/workspace/roles': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/access': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdAccessRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/general': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/gantt': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/device'
    | '/portal'
    | '/test-error'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/invoice/$invoiceId'
    | '/mcp/authorize'
    | '/post/$token'
    | '/device/'
    | '/activity'
    | '/administration'
    | '/board'
    | '/communications'
    | '/dashboard'
    | '/dialer'
    | '/emails'
    | '/employees'
    | '/finder'
    | '/home'
    | '/inbound'
    | '/inboxes'
    | '/invitations'
    | '/invoices'
    | '/leads'
    | '/marketing'
    | '/onboarding'
    | '/orders'
    | '/pipeline'
    | '/pipeline-settings'
    | '/profile-setup'
    | '/proposals'
    | '/scheduler'
    | '/invitation/accept/$inviteId'
    | '/portal/claim/$token'
    | '/proposal/$number/$slug'
    | '/s/t/$taskId'
    | '/dashboard/invitations'
    | '/dashboard/settings'
    | '/leads/kanban'
    | '/marketing/compose'
    | '/pipeline/$accountId'
    | '/proposals/$proposalId'
    | '/dashboard/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/projects'
    | '/dashboard/settings/workspace'
    | '/dashboard/workspace/$workspaceId'
    | '/dashboard/workspace/create'
    | '/dashboard/settings/account/developer'
    | '/dashboard/settings/account/information'
    | '/dashboard/settings/account/notifications'
    | '/dashboard/settings/account/preferences'
    | '/dashboard/settings/workspace/general'
    | '/dashboard/settings/workspace/labels'
    | '/dashboard/settings/workspace/roles'
    | '/dashboard/workspace/$workspaceId/members'
    | '/dashboard/workspace/$workspaceId/search'
    | '/dashboard/workspace/$workspaceId/'
    | '/dashboard/settings/projects/$projectId/access'
    | '/dashboard/settings/projects/$projectId/general'
    | '/dashboard/settings/projects/$projectId/integrations'
    | '/dashboard/settings/projects/$projectId/workflow'
    | '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
    | '/dashboard/workspace/$workspaceId/project/$projectId/board'
    | '/dashboard/workspace/$workspaceId/project/$projectId/gantt'
    | '/dashboard/workspace/$workspaceId/project/$projectId/'
    | '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/test-error'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/invoice/$invoiceId'
    | '/mcp/authorize'
    | '/post/$token'
    | '/device'
    | '/activity'
    | '/administration'
    | '/board'
    | '/communications'
    | '/dialer'
    | '/emails'
    | '/employees'
    | '/finder'
    | '/home'
    | '/inbound'
    | '/inboxes'
    | '/invitations'
    | '/invoices'
    | '/leads'
    | '/marketing'
    | '/onboarding'
    | '/orders'
    | '/pipeline'
    | '/pipeline-settings'
    | '/profile-setup'
    | '/proposals'
    | '/scheduler'
    | '/invitation/accept/$inviteId'
    | '/portal/claim/$token'
    | '/proposal/$number/$slug'
    | '/s/t/$taskId'
    | '/dashboard/invitations'
    | '/dashboard/settings'
    | '/leads/kanban'
    | '/marketing/compose'
    | '/pipeline/$accountId'
    | '/proposals/$proposalId'
    | '/dashboard'
    | '/dashboard/settings/account'
    | '/dashboard/settings/projects'
    | '/dashboard/settings/workspace'
    | '/dashboard/workspace/create'
    | '/dashboard/settings/account/developer'
    | '/dashboard/settings/account/information'
    | '/dashboard/settings/account/notifications'
    | '/dashboard/settings/account/preferences'
    | '/dashboard/settings/workspace/general'
    | '/dashboard/settings/workspace/labels'
    | '/dashboard/settings/workspace/roles'
    | '/dashboard/workspace/$workspaceId/members'
    | '/dashboard/workspace/$workspaceId/search'
    | '/dashboard/workspace/$workspaceId'
    | '/dashboard/settings/projects/$projectId/access'
    | '/dashboard/settings/projects/$projectId/general'
    | '/dashboard/settings/projects/$projectId/integrations'
    | '/dashboard/settings/projects/$projectId/workflow'
    | '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
    | '/dashboard/workspace/$workspaceId/project/$projectId/board'
    | '/dashboard/workspace/$workspaceId/project/$projectId/gantt'
    | '/dashboard/workspace/$workspaceId/project/$projectId'
    | '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/auth'
    | '/device'
    | '/portal'
    | '/test-error'
    | '/_layout/_authenticated'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/invoice/$invoiceId'
    | '/mcp/authorize'
    | '/post/$token'
    | '/device/'
    | '/_layout/_authenticated/activity'
    | '/_layout/_authenticated/administration'
    | '/_layout/_authenticated/board'
    | '/_layout/_authenticated/communications'
    | '/_layout/_authenticated/dashboard'
    | '/_layout/_authenticated/dialer'
    | '/_layout/_authenticated/emails'
    | '/_layout/_authenticated/employees'
    | '/_layout/_authenticated/finder'
    | '/_layout/_authenticated/home'
    | '/_layout/_authenticated/inbound'
    | '/_layout/_authenticated/inboxes'
    | '/_layout/_authenticated/invitations'
    | '/_layout/_authenticated/invoices'
    | '/_layout/_authenticated/leads'
    | '/_layout/_authenticated/marketing'
    | '/_layout/_authenticated/onboarding'
    | '/_layout/_authenticated/orders'
    | '/_layout/_authenticated/pipeline'
    | '/_layout/_authenticated/pipeline-settings'
    | '/_layout/_authenticated/profile-setup'
    | '/_layout/_authenticated/proposals'
    | '/_layout/_authenticated/scheduler'
    | '/invitation/accept/$inviteId'
    | '/portal/claim/$token'
    | '/proposal/$number/$slug'
    | '/s/t/$taskId'
    | '/_layout/_authenticated/dashboard/invitations'
    | '/_layout/_authenticated/dashboard/settings'
    | '/_layout/_authenticated/leads_/kanban'
    | '/_layout/_authenticated/marketing_/compose'
    | '/_layout/_authenticated/pipeline_/$accountId'
    | '/_layout/_authenticated/proposals_/$proposalId'
    | '/_layout/_authenticated/dashboard/'
    | '/_layout/_authenticated/dashboard/settings/account'
    | '/_layout/_authenticated/dashboard/settings/projects'
    | '/_layout/_authenticated/dashboard/settings/workspace'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId'
    | '/_layout/_authenticated/dashboard/workspace/create'
    | '/_layout/_authenticated/dashboard/settings/account/developer'
    | '/_layout/_authenticated/dashboard/settings/account/information'
    | '/_layout/_authenticated/dashboard/settings/account/notifications'
    | '/_layout/_authenticated/dashboard/settings/account/preferences'
    | '/_layout/_authenticated/dashboard/settings/workspace/general'
    | '/_layout/_authenticated/dashboard/settings/workspace/labels'
    | '/_layout/_authenticated/dashboard/settings/workspace/roles'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/access'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/general'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/gantt'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DeviceRoute: typeof DeviceRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  TestErrorRoute: typeof TestErrorRoute
  InvoiceInvoiceIdRoute: typeof InvoiceInvoiceIdRoute
  McpAuthorizeRoute: typeof McpAuthorizeRoute
  PostTokenRoute: typeof PostTokenRoute
  InvitationAcceptInviteIdRoute: typeof InvitationAcceptInviteIdRoute
  ProposalNumberSlugRoute: typeof ProposalNumberSlugRoute
  STTaskIdRoute: typeof STTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-error': {
      id: '/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/device/': {
      id: '/device/'
      path: '/'
      fullPath: '/device/'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/device/approve': {
      id: '/device/approve'
      path: '/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof DeviceApproveRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/invoice/$invoiceId': {
      id: '/invoice/$invoiceId'
      path: '/invoice/$invoiceId'
      fullPath: '/invoice/$invoiceId'
      preLoaderRoute: typeof InvoiceInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/authorize': {
      id: '/mcp/authorize'
      path: '/mcp/authorize'
      fullPath: '/mcp/authorize'
      preLoaderRoute: typeof McpAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$token': {
      id: '/post/$token'
      path: '/post/$token'
      fullPath: '/post/$token'
      preLoaderRoute: typeof PostTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated/activity': {
      id: '/_layout/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof LayoutAuthenticatedActivityRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/administration': {
      id: '/_layout/_authenticated/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof LayoutAuthenticatedAdministrationRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/board': {
      id: '/_layout/_authenticated/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof LayoutAuthenticatedBoardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/communications': {
      id: '/_layout/_authenticated/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof LayoutAuthenticatedCommunicationsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard': {
      id: '/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dialer': {
      id: '/_layout/_authenticated/dialer'
      path: '/dialer'
      fullPath: '/dialer'
      preLoaderRoute: typeof LayoutAuthenticatedDialerRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/emails': {
      id: '/_layout/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof LayoutAuthenticatedEmailsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/employees': {
      id: '/_layout/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof LayoutAuthenticatedEmployeesRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/finder': {
      id: '/_layout/_authenticated/finder'
      path: '/finder'
      fullPath: '/finder'
      preLoaderRoute: typeof LayoutAuthenticatedFinderRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/home': {
      id: '/_layout/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutAuthenticatedHomeRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/inbound': {
      id: '/_layout/_authenticated/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof LayoutAuthenticatedInboundRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/inboxes': {
      id: '/_layout/_authenticated/inboxes'
      path: '/inboxes'
      fullPath: '/inboxes'
      preLoaderRoute: typeof LayoutAuthenticatedInboxesRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/invitations': {
      id: '/_layout/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof LayoutAuthenticatedInvitationsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/invoices': {
      id: '/_layout/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof LayoutAuthenticatedInvoicesRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/leads': {
      id: '/_layout/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LayoutAuthenticatedLeadsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/marketing': {
      id: '/_layout/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof LayoutAuthenticatedMarketingRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/onboarding': {
      id: '/_layout/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof LayoutAuthenticatedOnboardingRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/orders': {
      id: '/_layout/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutAuthenticatedOrdersRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/pipeline': {
      id: '/_layout/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof LayoutAuthenticatedPipelineRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/pipeline-settings': {
      id: '/_layout/_authenticated/pipeline-settings'
      path: '/pipeline-settings'
      fullPath: '/pipeline-settings'
      preLoaderRoute: typeof LayoutAuthenticatedPipelineSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/profile-setup': {
      id: '/_layout/_authenticated/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof LayoutAuthenticatedProfileSetupRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/proposals': {
      id: '/_layout/_authenticated/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof LayoutAuthenticatedProposalsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/scheduler': {
      id: '/_layout/_authenticated/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof LayoutAuthenticatedSchedulerRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/invitation/accept/$inviteId': {
      id: '/invitation/accept/$inviteId'
      path: '/invitation/accept/$inviteId'
      fullPath: '/invitation/accept/$inviteId'
      preLoaderRoute: typeof InvitationAcceptInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/claim/$token': {
      id: '/portal/claim/$token'
      path: '/claim/$token'
      fullPath: '/portal/claim/$token'
      preLoaderRoute: typeof PortalClaimTokenRouteImport
      parentRoute: typeof PortalRoute
    }
    '/proposal/$number/$slug': {
      id: '/proposal/$number/$slug'
      path: '/proposal/$number/$slug'
      fullPath: '/proposal/$number/$slug'
      preLoaderRoute: typeof ProposalNumberSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/t/$taskId': {
      id: '/s/t/$taskId'
      path: '/s/t/$taskId'
      fullPath: '/s/t/$taskId'
      preLoaderRoute: typeof STTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated/dashboard/': {
      id: '/_layout/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/invitations': {
      id: '/_layout/_authenticated/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardInvitationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings': {
      id: '/_layout/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/leads_/kanban': {
      id: '/_layout/_authenticated/leads_/kanban'
      path: '/leads/kanban'
      fullPath: '/leads/kanban'
      preLoaderRoute: typeof LayoutAuthenticatedLeadsKanbanRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/marketing_/compose': {
      id: '/_layout/_authenticated/marketing_/compose'
      path: '/marketing/compose'
      fullPath: '/marketing/compose'
      preLoaderRoute: typeof LayoutAuthenticatedMarketingComposeRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/pipeline_/$accountId': {
      id: '/_layout/_authenticated/pipeline_/$accountId'
      path: '/pipeline/$accountId'
      fullPath: '/pipeline/$accountId'
      preLoaderRoute: typeof LayoutAuthenticatedPipelineAccountIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/proposals_/$proposalId': {
      id: '/_layout/_authenticated/proposals_/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof LayoutAuthenticatedProposalsProposalIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard/settings/account': {
      id: '/_layout/_authenticated/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects': {
      id: '/_layout/_authenticated/dashboard/settings/projects'
      path: '/projects'
      fullPath: '/dashboard/settings/projects'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace': {
      id: '/_layout/_authenticated/dashboard/settings/workspace'
      path: '/workspace'
      fullPath: '/dashboard/settings/workspace'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/dashboard/workspace/$workspaceId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/workspace/create': {
      id: '/_layout/_authenticated/dashboard/workspace/create'
      path: '/workspace/create'
      fullPath: '/dashboard/workspace/create'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceCreateRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/developer': {
      id: '/_layout/_authenticated/dashboard/settings/account/developer'
      path: '/developer'
      fullPath: '/dashboard/settings/account/developer'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/information': {
      id: '/_layout/_authenticated/dashboard/settings/account/information'
      path: '/information'
      fullPath: '/dashboard/settings/account/information'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/notifications': {
      id: '/_layout/_authenticated/dashboard/settings/account/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/account/notifications'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/preferences': {
      id: '/_layout/_authenticated/dashboard/settings/account/preferences'
      path: '/preferences'
      fullPath: '/dashboard/settings/account/preferences'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace/general': {
      id: '/_layout/_authenticated/dashboard/settings/workspace/general'
      path: '/general'
      fullPath: '/dashboard/settings/workspace/general'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace/labels': {
      id: '/_layout/_authenticated/dashboard/settings/workspace/labels'
      path: '/labels'
      fullPath: '/dashboard/settings/workspace/labels'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceLabelsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace/roles': {
      id: '/_layout/_authenticated/dashboard/settings/workspace/roles'
      path: '/roles'
      fullPath: '/dashboard/settings/workspace/roles'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/'
      path: '/'
      fullPath: '/dashboard/workspace/$workspaceId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/members': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
      path: '/members'
      fullPath: '/dashboard/workspace/$workspaceId/members'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/search': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
      path: '/search'
      fullPath: '/dashboard/workspace/$workspaceId/search'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/access': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/access'
      path: '/$projectId/access'
      fullPath: '/dashboard/settings/projects/$projectId/access'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdAccessRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/general': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/general'
      path: '/$projectId/general'
      fullPath: '/dashboard/settings/projects/$projectId/general'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations'
      path: '/$projectId/integrations'
      fullPath: '/dashboard/settings/projects/$projectId/integrations'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow'
      path: '/$projectId/workflow'
      fullPath: '/dashboard/settings/projects/$projectId/workflow'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog'
      path: '/project/$projectId/backlog'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board'
      path: '/project/$projectId/board'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/board'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/gantt': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/gantt'
      path: '/project/$projectId/gantt'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/gantt'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_'
      path: '/project/$projectId/task/$taskId'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
  }
}

interface LayoutAuthenticatedDashboardSettingsAccountRouteChildren {
  LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute: typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  LayoutAuthenticatedDashboardSettingsAccountInformationRoute: typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute: typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute: typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
}

const LayoutAuthenticatedDashboardSettingsAccountRouteChildren: LayoutAuthenticatedDashboardSettingsAccountRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute:
      LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute,
    LayoutAuthenticatedDashboardSettingsAccountInformationRoute:
      LayoutAuthenticatedDashboardSettingsAccountInformationRoute,
    LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute:
      LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute,
    LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute:
      LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute,
  }

const LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsAccountRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsAccountRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsProjectsRouteChildren {
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdAccessRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdAccessRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
}

const LayoutAuthenticatedDashboardSettingsProjectsRouteChildren: LayoutAuthenticatedDashboardSettingsProjectsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdAccessRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdAccessRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute,
  }

const LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsProjectsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsProjectsRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren {
  LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  LayoutAuthenticatedDashboardSettingsWorkspaceLabelsRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceLabelsRoute
  LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute
}

const LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren: LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute,
    LayoutAuthenticatedDashboardSettingsWorkspaceLabelsRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceLabelsRoute,
    LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute,
  }

const LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsWorkspaceRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsRouteChildren {
  LayoutAuthenticatedDashboardSettingsAccountRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  LayoutAuthenticatedDashboardSettingsProjectsRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  LayoutAuthenticatedDashboardSettingsWorkspaceRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
}

const LayoutAuthenticatedDashboardSettingsRouteChildren: LayoutAuthenticatedDashboardSettingsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAccountRoute:
      LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren,
    LayoutAuthenticatedDashboardSettingsProjectsRoute:
      LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren,
    LayoutAuthenticatedDashboardSettingsWorkspaceRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren,
  }

const LayoutAuthenticatedDashboardSettingsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsRouteChildren,
  )

interface LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren {
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren: LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren =
  {
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute,
  }

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute._addFileChildren(
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren,
  )

interface LayoutAuthenticatedDashboardRouteChildren {
  LayoutAuthenticatedDashboardInvitationsRoute: typeof LayoutAuthenticatedDashboardInvitationsRoute
  LayoutAuthenticatedDashboardSettingsRoute: typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  LayoutAuthenticatedDashboardIndexRoute: typeof LayoutAuthenticatedDashboardIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  LayoutAuthenticatedDashboardWorkspaceCreateRoute: typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
}

const LayoutAuthenticatedDashboardRouteChildren: LayoutAuthenticatedDashboardRouteChildren =
  {
    LayoutAuthenticatedDashboardInvitationsRoute:
      LayoutAuthenticatedDashboardInvitationsRoute,
    LayoutAuthenticatedDashboardSettingsRoute:
      LayoutAuthenticatedDashboardSettingsRouteWithChildren,
    LayoutAuthenticatedDashboardIndexRoute:
      LayoutAuthenticatedDashboardIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren,
    LayoutAuthenticatedDashboardWorkspaceCreateRoute:
      LayoutAuthenticatedDashboardWorkspaceCreateRoute,
  }

const LayoutAuthenticatedDashboardRouteWithChildren =
  LayoutAuthenticatedDashboardRoute._addFileChildren(
    LayoutAuthenticatedDashboardRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedActivityRoute: typeof LayoutAuthenticatedActivityRoute
  LayoutAuthenticatedAdministrationRoute: typeof LayoutAuthenticatedAdministrationRoute
  LayoutAuthenticatedBoardRoute: typeof LayoutAuthenticatedBoardRoute
  LayoutAuthenticatedCommunicationsRoute: typeof LayoutAuthenticatedCommunicationsRoute
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRouteWithChildren
  LayoutAuthenticatedDialerRoute: typeof LayoutAuthenticatedDialerRoute
  LayoutAuthenticatedEmailsRoute: typeof LayoutAuthenticatedEmailsRoute
  LayoutAuthenticatedEmployeesRoute: typeof LayoutAuthenticatedEmployeesRoute
  LayoutAuthenticatedFinderRoute: typeof LayoutAuthenticatedFinderRoute
  LayoutAuthenticatedHomeRoute: typeof LayoutAuthenticatedHomeRoute
  LayoutAuthenticatedInboundRoute: typeof LayoutAuthenticatedInboundRoute
  LayoutAuthenticatedInboxesRoute: typeof LayoutAuthenticatedInboxesRoute
  LayoutAuthenticatedInvitationsRoute: typeof LayoutAuthenticatedInvitationsRoute
  LayoutAuthenticatedInvoicesRoute: typeof LayoutAuthenticatedInvoicesRoute
  LayoutAuthenticatedLeadsRoute: typeof LayoutAuthenticatedLeadsRoute
  LayoutAuthenticatedMarketingRoute: typeof LayoutAuthenticatedMarketingRoute
  LayoutAuthenticatedOnboardingRoute: typeof LayoutAuthenticatedOnboardingRoute
  LayoutAuthenticatedOrdersRoute: typeof LayoutAuthenticatedOrdersRoute
  LayoutAuthenticatedPipelineRoute: typeof LayoutAuthenticatedPipelineRoute
  LayoutAuthenticatedPipelineSettingsRoute: typeof LayoutAuthenticatedPipelineSettingsRoute
  LayoutAuthenticatedProfileSetupRoute: typeof LayoutAuthenticatedProfileSetupRoute
  LayoutAuthenticatedProposalsRoute: typeof LayoutAuthenticatedProposalsRoute
  LayoutAuthenticatedSchedulerRoute: typeof LayoutAuthenticatedSchedulerRoute
  LayoutAuthenticatedLeadsKanbanRoute: typeof LayoutAuthenticatedLeadsKanbanRoute
  LayoutAuthenticatedMarketingComposeRoute: typeof LayoutAuthenticatedMarketingComposeRoute
  LayoutAuthenticatedPipelineAccountIdRoute: typeof LayoutAuthenticatedPipelineAccountIdRoute
  LayoutAuthenticatedProposalsProposalIdRoute: typeof LayoutAuthenticatedProposalsProposalIdRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedActivityRoute: LayoutAuthenticatedActivityRoute,
  LayoutAuthenticatedAdministrationRoute:
    LayoutAuthenticatedAdministrationRoute,
  LayoutAuthenticatedBoardRoute: LayoutAuthenticatedBoardRoute,
  LayoutAuthenticatedCommunicationsRoute:
    LayoutAuthenticatedCommunicationsRoute,
  LayoutAuthenticatedDashboardRoute:
    LayoutAuthenticatedDashboardRouteWithChildren,
  LayoutAuthenticatedDialerRoute: LayoutAuthenticatedDialerRoute,
  LayoutAuthenticatedEmailsRoute: LayoutAuthenticatedEmailsRoute,
  LayoutAuthenticatedEmployeesRoute: LayoutAuthenticatedEmployeesRoute,
  LayoutAuthenticatedFinderRoute: LayoutAuthenticatedFinderRoute,
  LayoutAuthenticatedHomeRoute: LayoutAuthenticatedHomeRoute,
  LayoutAuthenticatedInboundRoute: LayoutAuthenticatedInboundRoute,
  LayoutAuthenticatedInboxesRoute: LayoutAuthenticatedInboxesRoute,
  LayoutAuthenticatedInvitationsRoute: LayoutAuthenticatedInvitationsRoute,
  LayoutAuthenticatedInvoicesRoute: LayoutAuthenticatedInvoicesRoute,
  LayoutAuthenticatedLeadsRoute: LayoutAuthenticatedLeadsRoute,
  LayoutAuthenticatedMarketingRoute: LayoutAuthenticatedMarketingRoute,
  LayoutAuthenticatedOnboardingRoute: LayoutAuthenticatedOnboardingRoute,
  LayoutAuthenticatedOrdersRoute: LayoutAuthenticatedOrdersRoute,
  LayoutAuthenticatedPipelineRoute: LayoutAuthenticatedPipelineRoute,
  LayoutAuthenticatedPipelineSettingsRoute:
    LayoutAuthenticatedPipelineSettingsRoute,
  LayoutAuthenticatedProfileSetupRoute: LayoutAuthenticatedProfileSetupRoute,
  LayoutAuthenticatedProposalsRoute: LayoutAuthenticatedProposalsRoute,
  LayoutAuthenticatedSchedulerRoute: LayoutAuthenticatedSchedulerRoute,
  LayoutAuthenticatedLeadsKanbanRoute: LayoutAuthenticatedLeadsKanbanRoute,
  LayoutAuthenticatedMarketingComposeRoute:
    LayoutAuthenticatedMarketingComposeRoute,
  LayoutAuthenticatedPipelineAccountIdRoute:
    LayoutAuthenticatedPipelineAccountIdRoute,
  LayoutAuthenticatedProposalsProposalIdRoute:
    LayoutAuthenticatedProposalsProposalIdRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthRouteChildren {
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DeviceRouteChildren {
  DeviceApproveRoute: typeof DeviceApproveRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
}

const DeviceRouteChildren: DeviceRouteChildren = {
  DeviceApproveRoute: DeviceApproveRoute,
  DeviceIndexRoute: DeviceIndexRoute,
}

const DeviceRouteWithChildren =
  DeviceRoute._addFileChildren(DeviceRouteChildren)

interface PortalRouteChildren {
  PortalClaimTokenRoute: typeof PortalClaimTokenRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalClaimTokenRoute: PortalClaimTokenRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DeviceRoute: DeviceRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  TestErrorRoute: TestErrorRoute,
  InvoiceInvoiceIdRoute: InvoiceInvoiceIdRoute,
  McpAuthorizeRoute: McpAuthorizeRoute,
  PostTokenRoute: PostTokenRoute,
  InvitationAcceptInviteIdRoute: InvitationAcceptInviteIdRoute,
  ProposalNumberSlugRoute: ProposalNumberSlugRoute,
  STTaskIdRoute: STTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
